name: Build & deploy server
on:
  push:
    branches: [ dev ]

jobs:
  build-windows:
    name: Build windows release
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract version
        id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=BRANCH::${TAG/\/*}
          echo ::set-output name=VERSION::${TAG/*\/}

      - name: Build
        shell: cmd
        run: |
          cd server
          build.bat 0 %VERSION%
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Copy files
        shell: cmd
        run: |
          cd server
          mkdir upload\modules\js-module
          copy dist\js-module.dll upload\modules\js-module
          copy dist\libnode.dll upload\modules\js-module

      - uses: actions/upload-artifact@v2
        with:
          name: js-module-windows
          path: ./server/upload/

  build-linux:
    name: Build linux release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract version
        id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=BRANCH::${TAG/\/*}
          echo ::set-output name=VERSION::${TAG/*\/}

      - name: Build
        run: |
          cd server
          ./build.sh %VERSION%
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Copy files
        run: |
          cd server
          mkdir -p upload/modules/js-module
          cp ./dist/libjs-module.so ./upload/modules/js-module
          cp ./dist/libnode.so.102 ./upload/modules/js-module

      - uses: actions/upload-artifact@v2
        with:
          name: js-module-linux
          path: ./server/upload/

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-18.04
    needs: [build-linux, build-windows]
    steps:
      - name: Download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: js-module-windows
          path: dist-windows

      - name: Download linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: js-module-linux
          path: dist-linux

      - name: Zip artifacts
        run: |
          zip -r -j js-module-windows dist-windows
          zip -r -j js-module-linux dist-linux

      - name: Extract version
        id: version
        shell: bash
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=BRANCH::${TAG/\/*}
          echo ::set-output name=VERSION::${TAG/*\/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.VERSION }}

      - name: Upload windows artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./js-module-windows.zip
          asset_name: js-module-windows.zip
          asset_content_type: application/zip

      - name: Upload linux artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./js-module-linux.zip
          asset_name: js-module-linux.zip
          asset_content_type: application/zip

  delete-artifacts:
    name: Delete artifacts
    runs-on: ubuntu-18.04
    needs: [ create-release ]
    if: ${{ always() }}
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            js-module-linux
            js-module-windows
